
int8 TAG = 1
int8 WAIT_TAG = 2
int8 STOP = 11
int8 PAUSE = 12
int8 RESUME = 13

int8 EXIT = -1

int8 PVT_ENTER_JOINT = 20
int8 PVT_ENTER_TOOL = 21
int8 PVT_EXIT = 22
int8 PVT_PAUSE = 23
int8 PVT_RESUME = 24

# request fields

int8 func

int8 arg0
int8 arg1

---
bool ok

# int8 rv
