# mode - JOINT or CARTESIAN
# More details please refer to Expression Editor and Listen Node_1.80_Rev1.00_EN.pdf Chapter 8.18
int8 JOINT = 1
int8 TOOL = 2

int8 mode
tmr_msgs/PvtPosition[] positions
---
# ok :  set motion status 
bool ok